apiVersion: v1
kind: ServiceAccount
metadata:
  name: kongdev # ServiceAccount Name
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kongdev-cluster-admin # ClusterRoleBinding name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kongdev # ชื่อเดียวกับ ServiceAccount
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: kongdev-secrets
  namespace: default
  annotations:
    kubernetes.io/service-account.name: kongdev # ชื่อเดียวกับ ServiceAccount
type: kubernetes.io/service-account-token
